[package]
name = "dm_proto"
version = "0.1.0"
authors = ["DeFv destinyfunk@163.com"]
description = "data-mind's data protobuf def"
edition = "2024"

[dependencies]
bytes = "1.10.1"
prost = "0.13.5"
prost-types = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
